
default: &default
  adapter: postgresql
  # adapter: mysql2
  # To use mysql uncomment the above and add the line below to the gemfile
  # gem 'mysql2'
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: admin_browser_development
  username: <%= ENV['DB_USER']%>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: admin_browser_test
  username: <%= ENV['DB_USER']%>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  database: admin_browser_production
  username: admin_browser
  password: <%= ENV['ADMIN_BROWSER_DATABASE_PASSWORD'] %>
